### ISSUE TITLE
remove `rom0:FONTM` dependency

### ISSUE THREAD

**Issue by israpps** [382kB/NanoPS2#1]
https://github.com/382kB/NanoPS2/blob/9a976e37844931599eea6c0bce8f42f1e793503b/system.lua#L1

Would be cool if replaced by an actual TTF font for those consoles that dont have `rom0:FONTM`

**Comment by 382kB** [comment]
do you have any idea? I tested it and it's a little more complicated. I wasn't successful and the Enceladus documentation isn't that clear :/

**Comment by israpps** [comment]
> do you have any idea? I tested it and it's a little more complicated. I wasn't successful and the Enceladus documentation isn't that clear :/

its not that complicated:
```lua
Font.ftInit()
myfont = Font.ftLoad("foo.ttf")
Font.ftPrint(myfont , x, y, align, width, height, "hello world", color)
-- align: 0 for left align, 8 for centered
-- width and height define a draw area, if text surpasses it the portion that exceeded the area is not written
```

**Comment by 382kB** [comment]
thanks. I updated and tested the code and it worked
